### PR TITLE
AtlasV(vb), (ProfanityFilter, Classic Telnet) added to both

### PR DESCRIPTION
**Pull request by OneMeanDragon**
Edit: Since this comment doesn't need to be here now, due to how far along the pull has spanned.

### CODE REVIEW

**Comment by carlbennett** [comment]
I have questions.

- What was the purpose of converting this project from csharp to vb, then adding the vb version side-by-side the csharp version? What does this solve and why should this be accepted? I don't recall a prior conversation.
- What is "AtlasV"? What does the "V" mean?
- The commit log messages could be cleaned up, the messages seem to get reused in multiple commits, so I'm not sure what each commit adds.

> note that your 0..^2 voodoo wont be present in VB.

I'm not sure what voodoo you're referring to. Perhaps a version constraint somewhere? I'm not really sure.

**Comment by carlbennett** [comment]
The message in commit 3303575b3ce967d4fe10a39f4e978e96cc7cbd31 seems to suggest this effort was made in part to convert the existing code to .NET Core 5.0, but it doesn't answer for the other questions.

**Comment by OneMeanDragon** [comment]
> The message in commit [3303575](https://github.com/BNETDocs/Atlas/commit/3303575b3ce967d4fe10a39f4e978e96cc7cbd31) seems to suggest this effort was made in part to convert the existing code to .NET Core 5.0, but it doesn't answer for the other questions.

It's because I'm building side by side, whatever I add to the VB section I'm adding to the C# section, the VB section is there because C# gives me tunnel vision. also yours will likely build on 5.0 as well. and I need to reset up git again it looks like, or do my uploads in order heh.

**Comment by OneMeanDragon** [comment]
Something to consider at a later time would be to expand the following
`public static byte[] FilterMessage(byte[] varByteArray)`
with an optional bool controlled by the user account (a bot with access to edit profile keys, create a key to hold a bool for activating and deactivating the in chat filter, just remember by default this would be on)

**Comment by OneMeanDragon** [comment]
And there's Classic Telnet.

**Pull request closed without merging**
